# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 00:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('improve', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='offer',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='effect',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='profit',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 24, 0, 23, 3, 837597, tzinfo=utc)),
        ),
    ]
